[package]
name = "Raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
rand = "0.8"
rayon = "1.10.0"
indicatif = "0.17"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"